MAIN := stlc
OBJS := ast.cmo lexer.cmo parser.cmo pprint.cmo eval.cmo check.cmo main.cmo

%.cmo: %.ml
	ocamlc -c $<

%.cmi: %.mli
	ocamlc -c $<

$(MAIN): $(OBJS)
	ocamlc -o $@ $^

lexer.ml: lexer.mll
	ocamllex -q $<

parser.ml: parser.mly
	ocamlyacc -v $<

parser.mli: parser.mly
	ocamlyacc -v $<

clean:
	rm -f *.cmo *.cmi lexer.ml parser.ml parser.mli $(MAIN)

# Dependencies generated by `ocamldep -bytecode *.mli *.ml`.
ast.cmo :
check.cmo : ast.cmo
eval.cmo : ast.cmo
lexer.cmo : parser.cmi
main.cmo : pprint.cmo parser.cmi lexer.cmo eval.cmo check.cmo ast.cmo
parser.cmo : ast.cmo parser.cmi
parser.cmi : ast.cmo
pprint.cmo : ast.cmo
