default: build
	utop

build:
	ocamlbuild lexer.mll
	ocamlbuild parser.mly
	# ocamlbuild -use-ocamlfind main.byte

# test:
# 	ocamlbuild -use-ocamlfind test.byte && ./test.byte

# clean:
# 	ocamlbuild -clean
